#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mongo-express"
name = "Mongo Express"
description.en = "Admin server for Mongo and optionally Mongo database"
description.fr = "Serveur d'administration pour Mongo ainsi qu'optionnellement une base Mongo"

version = "1.0.2~ynh1"

maintainers = ["Gerard Collin"]

[upstream]
license = "MIT"
code = "https://github.com/mongo-express/mongo-express"
cpe = "cpe:2.3:a:mongo-express_project:mongo-express"

[integration]
yunohost = ">= 11.2.12"
architectures = ["amd64"]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mongo"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.mongo_version]
    ask.en = "Select the major version of Mongo to install or 'None' if already installed"
    ask.fr = "Choisissez la version de Mongo a installer ou 'None' si Mongo est déjà installé"
    type = "select"
    choices = ["None", "4.4", "5.0", "6.0"]
    default = "6.0"

[resources]
    [resources.sources.main]
    url = "https://github.com/mongo-express/mongo-express/archive/refs/tags/v1.0.2.tar.gz"
    sha256 = "c60a764aa71d37c18ec2bb6db8fe77356ca3bdbd91fa70a893106de1632640a1"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8096
