#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mongo-express"
name = "Mongo Express"
description.en = "Admin server for Mongo and optionally Mongo database"
description.fr = "Serveur d'administration pour Mongo ainsi qu'optionnellement une base Mongo"

version = "1.1.0-rc-4~ynh1"

maintainers = ["Gerard Collin"]

[upstream]
license = "MIT"
code = "https://github.com/mongo-express/mongo-express"
cpe = "cpe:2.3:a:mongo-express_project:mongo-express"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
[install.domain]
type = "domain"

[install.path]
type = "path"
default = "/mongo"

[install.init_main_permission]
type = "group"
default = "visitors"

[resources]
[resources.sources.main]
url = "https://github.com/gcollin/mongo-express/releases/download/v1.1.0-rc-4/mongo-express-1.1.0-rc-4.tgz"
sha256 = "2e2a1bed38b9337cb0e7155e6a11f07f74fca24a672019ac0b54080993c4d39c"

autoupdate.strategy = "latest_github_release"
autoupdate.asset = "tarball"

[resources.system_user]

[resources.install_dir]

[resources.data_dir]

[resources.permissions]
main.url = "/"

[resources.ports]
main.default = 8096

[resources.nodejs]
version = "20"
